"""
Clinically revised DB-shaped transcript fixtures for the current APEX backend.

Revisions applied after clinician-style review:
- GOOD turn 1 setting question treated as closed-option rather than open.
- Family-history appraisal spans shifted from Judgment to Appreciation where more clinically natural.
- BAD turn 6 seriousness appraisal shifted toward Appreciation.
- GOOD turn 15 supportive commitment labeled response type "other" rather than "understanding".
- relations_json populated on key turns to illustrate EO->response / EO->elicitation links.
"""

TEST_CONVERSATION_BAD = {'name': 'bad_missed_empathy_sparse_spikes',
 'label': 'BAD',
 'transcript': [{'role': 'user',
                 'turn_number': 1,
                 'text': "Let's get started. What brings you here?",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': None,
                 'expected_question_type': 'open'},
                {'role': 'assistant',
                 'turn_number': 2,
                 'text': "I've been really tired and scared because my symptoms seem to be getting "
                         'worse.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1200.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'scared',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'my symptoms seem to be getting worse',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 3,
                 'text': 'Well, symptoms fluctuate. Anyway, when did it start?',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'closed',
                                  'tone': {'calm': False, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': None,
                 'expected_question_type': 'closed'},
                {'role': 'assistant',
                 'turn_number': 4,
                 'text': "About a month ago. It's been affecting my sleep and I'm worried "
                         'something serious is going on.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1100.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'affecting my sleep',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'worried',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 5,
                 'text': "Worrying won't help. Did you take the meds I prescribed?",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'closed',
                                  'tone': {'calm': False, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': None,
                 'expected_question_type': 'closed'},
                {'role': 'assistant',
                 'turn_number': 6,
                 'text': "Yes, but they aren't helping and I feel like something is really wrong.",
                 'metrics_json': {'empathy_opportunity_type': 'implicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1000.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'something is really wrong',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 7,
                 'text': "Okay, noted. Let's move on. Any chest pain?",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'closed',
                                  'tone': {'calm': False, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': None,
                 'expected_question_type': 'closed'},
                {'role': 'assistant',
                 'turn_number': 8,
                 'text': 'Sometimes, and it scares me a lot. My dad had heart issues.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 950.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'it scares me a lot',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'My dad had heart issues',
                                 'confidence': 0.75,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 9,
                 'text': 'Family history is common. Chest pain can be many things.',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'knowledge',
                 'expected_question_type': 'statement'},
                {'role': 'assistant',
                 'turn_number': 10,
                 'text': "I feel overwhelmed. I don't know what to expect.",
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1050.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'overwhelmed',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 11,
                 'text': "I'll explain everything after tests. There's no point stressing about it "
                         'now.',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'statement',
                                  'tone': {'calm': False, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'knowledge',
                 'expected_question_type': 'statement'},
                {'role': 'assistant',
                 'turn_number': 12,
                 'text': 'I just... feel alone in this.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1025.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'feel alone',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 13,
                 'text': "Well, we're doing what we can. Let's schedule the bloodwork.",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'strategy',
                 'expected_question_type': 'statement'}],
 'expected_feedback': {'score_ranges': {'empathy_score': [0, 35],
                                        'communication_score': [0, 45],
                                        'clinical_reasoning_score': [0, 50],
                                        'professionalism_score': [0, 60],
                                        'overall_score': [0, 45],
                                        'spikes_completion_score': [0, 40]},
                       'eo_counts_by_dimension_min': {'Feeling': 4, 'Appreciation': 4},
                       'elicitation_counts_by_type_max': {'direct': 0, 'indirect': 0},
                       'response_counts_by_type_max': {'understanding': 0,
                                                       'acceptance': 0,
                                                       'sharing': 0},
                       'missed_opportunities_min': 5,
                       'suggested_responses_min': 4,
                       'timeline_events_min': 4,
                       'spikes_expected_present': ['knowledge', 'strategy'],
                       'spikes_expected_absent': ['setting', 'perception', 'invitation', 'emotion'],
                       'question_breakdown_min': {'closed': 3},
                       'linkage_stats': {'response_link_rate_max': 0.2}}}

TEST_CONVERSATION_MEDIUM = {'name': 'medium_partial_empathy_partial_spikes',
 'label': 'MEDIUM',
 'transcript': [{'role': 'user',
                 'turn_number': 1,
                 'text': 'Thanks for coming in. Is this still a good time to talk?',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'closed',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'setting',
                 'expected_question_type': 'closed'},
                {'role': 'assistant',
                 'turn_number': 2,
                 'text': "Yes, but I'm pretty anxious. My symptoms have been getting worse.",
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1200.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'pretty anxious',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'my symptoms have been getting worse',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 3,
                 'text': "I'm sorry it's been stressful. Can you tell me what has been getting "
                         'worse?',
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['sorry'],
                                              'has_empathy': True},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'direct',
                                 'dimension': 'Appreciation',
                                 'text': 'Can you tell me what has been getting worse?',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'elicitation'},
                                {'type': 'understanding',
                                 'text': "I'm sorry it's been stressful",
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 2,
                                     'target_turn_number': 3,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'},
                                    {'source_turn_number': 2,
                                     'target_turn_number': 3,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'elicitation',
                                     'relation': 'explored_by'}],
                 'expected_spikes': 'perception',
                 'expected_question_type': 'open',
                 'expected_links_from_turns': [2]},
                {'role': 'assistant',
                 'turn_number': 4,
                 'text': 'Mostly the fatigue and this pressure in my chest.',
                 'metrics_json': {'empathy_opportunity_type': 'implicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 950.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'fatigue and this pressure in my chest',
                                 'confidence': 0.78,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 5,
                 'text': "I see. We'll sort through it.",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': None,
                 'expected_question_type': 'statement'},
                {'role': 'assistant',
                 'turn_number': 6,
                 'text': 'I barely sleep anymore. I keep thinking something serious is happening.',
                 'metrics_json': {'empathy_opportunity_type': 'implicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 900.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'I barely sleep anymore',
                                 'confidence': 0.78,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Feeling',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'I keep thinking something serious is happening',
                                 'confidence': 0.78,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 7,
                 'text': 'That sounds difficult. Have you been taking your meds?',
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['difficult'],
                                              'has_empathy': True},
                                  'question_type': 'closed',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'understanding',
                                 'text': 'That sounds difficult',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 6,
                                     'target_turn_number': 7,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': None,
                 'expected_question_type': 'closed',
                 'expected_links_from_turns': [6]},
                {'role': 'assistant',
                 'turn_number': 8,
                 'text': "Yes, but it doesn't help my fear. My dad had heart problems.",
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 875.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': "doesn't help my fear",
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'My dad had heart problems',
                                 'confidence': 0.75,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': [{'source_turn_number': 8,
                                     'target_turn_number': 9,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}]},
                {'role': 'user',
                 'turn_number': 9,
                 'text': 'I understand that family history can make this feel scarier.',
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['understand', 'feel'],
                                              'has_empathy': True},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'understanding',
                                 'text': 'I understand that family history can make this feel '
                                         'scarier',
                                 'confidence': 0.82,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 8,
                                     'target_turn_number': 9,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': 'emotion',
                 'expected_question_type': 'statement',
                 'expected_links_from_turns': [8]},
                {'role': 'assistant',
                 'turn_number': 10,
                 'text': "Exactly. I'm overwhelmed.",
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 850.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'overwhelmed',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 11,
                 'text': "Let's take this step by step. I'll explain what tests can help us "
                         "understand what's going on.",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'knowledge',
                 'expected_question_type': 'statement'},
                {'role': 'assistant',
                 'turn_number': 12,
                 'text': 'Okay. I appreciate that.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 825.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'I appreciate that',
                                 'confidence': 0.82,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 13,
                 'text': "Before we move on, is there anything else you're hoping to understand "
                         'today?',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [{'type': 'direct',
                                 'dimension': 'Appreciation',
                                 'text': "is there anything else you're hoping to understand "
                                         'today?',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'elicitation'}],
                 'relations_json': [{'source_turn_number': 12,
                                     'target_turn_number': 13,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'elicitation',
                                     'relation': 'explored_by'}],
                 'expected_spikes': 'invitation',
                 'expected_question_type': 'open'}],
'expected_feedback': {'score_ranges': {'empathy_score': [35, 80],
                                        'communication_score': [45, 80],
                                        'clinical_reasoning_score': [40, 80],
                                        'professionalism_score': [55, 90],
                                        'overall_score': [45, 80],
                                        'spikes_completion_score': [35, 75]},
                       'eo_counts_by_dimension_min': {'Feeling': 4, 'Appreciation': 4},
                       'elicitation_counts_by_type_min': {'direct': 2},
                       'response_counts_by_type_min': {'understanding': 3},
                       'missed_opportunities_range': [1, 5],
                       'suggested_responses_range': [1, 4],
                       'timeline_events_min': 4,
                       'spikes_expected_present': ['setting',
                                                   'perception',
                                                   'knowledge',
                                                   'invitation',
                                                   'emotion'],
                       'spikes_expected_absent': ['strategy'],
                       'question_breakdown_min': {'open': 2, 'closed': 2},
                       'linkage_stats': {'response_link_rate_min': 0.3,
                                         'response_link_rate_max': 0.8}}}

TEST_CONVERSATION_GOOD = {'name': 'good_strong_empathy_complete_spikes',
 'label': 'GOOD',
 'transcript': [{'role': 'user',
                 'turn_number': 1,
                 'text': "Thanks for meeting with me. I want to make sure you're comfortable. Can "
                         'we talk here, or would you prefer a quieter room?',
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'closed',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [],
                 'relations_json': None,
                 'expected_spikes': 'setting',
                 'expected_question_type': 'closed'},
                {'role': 'assistant',
                 'turn_number': 2,
                 'text': "Here is okay. I'm feeling anxious, and my symptoms have been getting "
                         'worse.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 1000.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'anxious',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'my symptoms have been getting worse',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 3,
                 'text': "I hear you. It makes sense you'd feel anxious. Can you tell me what "
                         'symptoms have been getting worse?',
                 'metrics_json': {'empathy': {'empathy_score': 5.0,
                                              'found_keywords': ['hear', 'feel'],
                                              'has_empathy': True},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'understanding',
                                 'text': 'I hear you',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'},
                                {'type': 'acceptance',
                                 'text': "It makes sense you'd feel anxious",
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'},
                                {'type': 'direct',
                                 'dimension': 'Appreciation',
                                 'text': 'Can you tell me what symptoms have been getting worse?',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'elicitation'}],
                 'relations_json': [{'source_turn_number': 2,
                                     'target_turn_number': 3,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'},
                                    {'source_turn_number': 2,
                                     'target_turn_number': 3,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'elicitation',
                                     'relation': 'explored_by'}],
                 'expected_spikes': 'perception',
                 'expected_question_type': 'open',
                 'expected_links_from_turns': [2]},
                {'role': 'assistant',
                 'turn_number': 4,
                 'text': "Mostly the fatigue and this pressure in my chest. It's been really "
                         'scary.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 950.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'the fatigue and this pressure in my chest',
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'scary',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 5,
                 'text': 'I understand how frightening that can be.',
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['understand'],
                                              'has_empathy': True},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'understanding',
                                 'text': 'I understand how frightening that can be',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 4,
                                     'target_turn_number': 5,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': 'emotion',
                 'expected_question_type': 'statement',
                 'expected_links_from_turns': [4]},
                {'role': 'assistant',
                 'turn_number': 6,
                 'text': "And I hardly sleep. I'm afraid something serious is happening.",
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 900.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'I hardly sleep',
                                 'confidence': 0.78,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'afraid',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 7,
                 'text': "It makes sense that you'd feel afraid. Can you tell me what part feels "
                         'the hardest?',
                 'metrics_json': {'empathy': {'empathy_score': 5.0,
                                              'found_keywords': ['feel'],
                                              'has_empathy': True},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'acceptance'},
                 'spans_json': [{'type': 'acceptance',
                                 'text': "It makes sense that you'd feel afraid",
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'},
                                {'type': 'direct',
                                 'dimension': 'Feeling',
                                 'text': 'Can you tell me what part feels the hardest?',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'elicitation'}],
                 'relations_json': [{'source_turn_number': 6,
                                     'target_turn_number': 7,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'},
                                    {'source_turn_number': 6,
                                     'target_turn_number': 7,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'elicitation',
                                     'relation': 'explored_by'}],
                 'expected_spikes': 'emotion',
                 'expected_question_type': 'open',
                 'expected_links_from_turns': [6]},
                {'role': 'assistant',
                 'turn_number': 8,
                 'text': 'My dad had heart problems, so every sensation makes me feel scared.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 875.0},
                 'spans_json': [{'dimension': 'Appreciation',
                                 'explicit_or_implicit': 'implicit',
                                 'text': 'My dad had heart problems',
                                 'confidence': 0.75,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'},
                                {'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'scared',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 9,
                 'text': 'Thank you for telling me that. I understand how that history would make '
                         'this even more stressful.',
                 'metrics_json': {'empathy': {'empathy_score': 5.0,
                                              'found_keywords': ['thank', 'understand'],
                                              'has_empathy': True},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'acceptance',
                                 'text': 'Thank you for telling me that',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'},
                                {'type': 'understanding',
                                 'text': 'I understand how that history would make this even more '
                                         'stressful',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 8,
                                     'target_turn_number': 9,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': 'emotion',
                 'expected_question_type': 'statement',
                 'expected_links_from_turns': [8]},
                {'role': 'assistant',
                 'turn_number': 10,
                 'text': 'Yeah... I feel overwhelmed.',
                 'metrics_json': {'empathy_opportunity_type': 'explicit',
                                  'empathy_opportunity': True,
                                  'latency_ms': 850.0},
                 'spans_json': [{'dimension': 'Feeling',
                                 'explicit_or_implicit': 'explicit',
                                 'text': 'overwhelmed',
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'eo'}],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 11,
                 'text': 'I hear that. Let me walk through what we know so far and what tests can '
                         'help clarify things.',
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['hear'],
                                              'has_empathy': True},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'understanding'},
                 'spans_json': [{'type': 'understanding',
                                 'text': 'I hear that',
                                 'confidence': 0.82,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 10,
                                     'target_turn_number': 11,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': 'knowledge',
                 'expected_question_type': 'statement',
                 'expected_links_from_turns': [10]},
                {'role': 'assistant',
                 'turn_number': 12,
                 'text': 'Okay, that helps.',
                 'metrics_json': {'empathy_opportunity_type': None,
                                  'empathy_opportunity': False,
                                  'latency_ms': 800.0},
                 'spans_json': [],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 13,
                 'text': "Before I summarize next steps, can you tell me if there's anything "
                         "important you haven't shared yet?",
                 'metrics_json': {'empathy': {'empathy_score': 0.0,
                                              'found_keywords': [],
                                              'has_empathy': False},
                                  'question_type': 'open',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': False,
                                  'empathy_response_type': 'other'},
                 'spans_json': [{'type': 'direct',
                                 'dimension': 'Appreciation',
                                 'text': "Can you tell me if there's anything important you "
                                         "haven't shared yet?",
                                 'confidence': 0.85,
                                 'provenance': 'fixture',
                                 'span_type': 'elicitation'}],
                 'relations_json': [{'source_turn_number': 12,
                                     'target_turn_number': 13,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'elicitation',
                                     'relation': 'explored_by'}],
                 'expected_spikes': 'invitation',
                 'expected_question_type': 'open'},
                {'role': 'assistant',
                 'turn_number': 14,
                 'text': 'No, that covers it. Thank you.',
                 'metrics_json': {'empathy_opportunity_type': None,
                                  'empathy_opportunity': False,
                                  'latency_ms': 775.0},
                 'spans_json': [],
                 'relations_json': None},
                {'role': 'user',
                 'turn_number': 15,
                 'text': "Here's our plan: we'll check your heart, review your symptoms together "
                         "afterward, and I'll support you through every step.",
                 'metrics_json': {'empathy': {'empathy_score': 2.5,
                                              'found_keywords': ['support'],
                                              'has_empathy': True},
                                  'question_type': 'statement',
                                  'tone': {'calm': True, 'clear': True},
                                  'empathy_response': True,
                                  'empathy_response_type': 'other'},
                 'spans_json': [{'type': 'other',
                                 'text': "I'll support you through every step",
                                 'confidence': 0.8,
                                 'provenance': 'fixture',
                                 'span_type': 'response'}],
                 'relations_json': [{'source_turn_number': 14,
                                     'target_turn_number': 15,
                                     'source_span_type': 'eo',
                                     'target_span_type': 'response',
                                     'relation': 'addressed_by'}],
                 'expected_spikes': 'strategy',
                 'expected_question_type': 'statement'}],
 'expected_feedback': {'score_ranges': {'empathy_score': [70, 100],
                                        'communication_score': [70, 100],
                                        'clinical_reasoning_score': [65, 100],
                                        'professionalism_score': [75, 100],
                                        'overall_score': [70, 100],
                                        'spikes_completion_score': [70, 100]},
                       'eo_counts_by_dimension_min': {'Feeling': 5, 'Appreciation': 4},
                       'elicitation_counts_by_type_min': {'direct': 3},
                       'response_counts_by_type_min': {'understanding': 4, 'acceptance': 3},
                       'missed_opportunities_max': 2,
                       'suggested_responses_max': 2,
                       'timeline_events_min': 6,
                       'spikes_expected_present': ['setting',
                                                   'perception',
                                                   'knowledge',
                                                   'invitation',
                                                   'emotion',
                                                   'strategy'],
                       'question_breakdown_min': {'open': 4},
                       'linkage_stats': {'response_link_rate_min': 0.7}}}

