"""add_expanded_feedback_metrics

Revision ID: dabe018eb7d3
Revises: 3b489e98e21d
Create Date: 2025-11-13 20:01:37.069614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabe018eb7d3'
down_revision: Union[str, None] = '3b489e98e21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('eo_counts', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('elicitation_count', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('empathy_response_count', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('linkage_stats', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('missed_opportunities', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('response_types', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('spikes_timestamps', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('spikes_strategies', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('question_breakdown', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('interruptions', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('reflections_interpretations', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('tone_summary', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('prohibited_behaviors', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('deescalation_strategies', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('bias_probe_info', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('evaluator_meta', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('latency_ms_avg', sa.Float(), nullable=True))
    op.drop_column('feedback', 'reassurance_moments')
    op.drop_column('feedback', 'empathy_spikes')
    op.drop_column('feedback', 'question_ratios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('question_ratios', sa.TEXT(), nullable=True))
    op.add_column('feedback', sa.Column('empathy_spikes', sa.TEXT(), nullable=True))
    op.add_column('feedback', sa.Column('reassurance_moments', sa.TEXT(), nullable=True))
    op.drop_column('feedback', 'latency_ms_avg')
    op.drop_column('feedback', 'evaluator_meta')
    op.drop_column('feedback', 'bias_probe_info')
    op.drop_column('feedback', 'deescalation_strategies')
    op.drop_column('feedback', 'prohibited_behaviors')
    op.drop_column('feedback', 'tone_summary')
    op.drop_column('feedback', 'reflections_interpretations')
    op.drop_column('feedback', 'interruptions')
    op.drop_column('feedback', 'question_breakdown')
    op.drop_column('feedback', 'spikes_strategies')
    op.drop_column('feedback', 'spikes_timestamps')
    op.drop_column('feedback', 'response_types')
    op.drop_column('feedback', 'missed_opportunities')
    op.drop_column('feedback', 'linkage_stats')
    op.drop_column('feedback', 'empathy_response_count')
    op.drop_column('feedback', 'elicitation_count')
    op.drop_column('feedback', 'eo_counts')
    # ### end Alembic commands ###

